/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PalavrasBloqueadasRouteImport } from './routes/palavras-bloqueadas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfertaIdRouteImport } from './routes/oferta.$id'

const PalavrasBloqueadasRoute = PalavrasBloqueadasRouteImport.update({
  id: '/palavras-bloqueadas',
  path: '/palavras-bloqueadas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaIdRoute = OfertaIdRouteImport.update({
  id: '/oferta/$id',
  path: '/oferta/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/palavras-bloqueadas': typeof PalavrasBloqueadasRoute
  '/oferta/$id': typeof OfertaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/palavras-bloqueadas': typeof PalavrasBloqueadasRoute
  '/oferta/$id': typeof OfertaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/palavras-bloqueadas': typeof PalavrasBloqueadasRoute
  '/oferta/$id': typeof OfertaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/palavras-bloqueadas' | '/oferta/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/palavras-bloqueadas' | '/oferta/$id'
  id: '__root__' | '/' | '/palavras-bloqueadas' | '/oferta/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PalavrasBloqueadasRoute: typeof PalavrasBloqueadasRoute
  OfertaIdRoute: typeof OfertaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/palavras-bloqueadas': {
      id: '/palavras-bloqueadas'
      path: '/palavras-bloqueadas'
      fullPath: '/palavras-bloqueadas'
      preLoaderRoute: typeof PalavrasBloqueadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta/$id': {
      id: '/oferta/$id'
      path: '/oferta/$id'
      fullPath: '/oferta/$id'
      preLoaderRoute: typeof OfertaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PalavrasBloqueadasRoute: PalavrasBloqueadasRoute,
  OfertaIdRoute: OfertaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
